#!/bin/bash

# Description: Link dotfiles to home directory

#mkdir -p ~/.config

dotfiles=("bashrc" "vimrc" "starship.toml")

for file in "${dotfiles[@]}"; do
	if [ "$file" == starship.toml ]; then
		ln -sf ~/dotfiles/"$file" ~/.config/"$file"
	else
		ln -sf ~/dotfiles/"$file" ~/."$file"
	fi
done

#ln -sf ~/dotfiles/bashrc ~/.bashrc
#ln -sf ~/dotfiles/vimrc ~/.vimrc
#ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

echo "Dotfiles linked!"
