#!/bin/bash

# Description: Link dotfiles to home directory

#mkdir -p ~/.config

dotfiles=("bashrc" "vimrc")

for file in "${dotfiles[@]}"; do
	ln -sf ~/dotfiles/"$file" ~/."$file"
done

#ln -sf ~/dotfiles/bashrc ~/.bashrc
#ln -sf ~/dotfiles/vimrc ~/.vimrc
#ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

echo "Dotfiles linked!"
